development:
  url:  <%= ENV["DATABASE_URL"] || "mysql2://root@localhost" %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: tiny_mini

test: &test
  url:  <%= ENV["DATABASE_URL"] || "mysql2://root@localhost" %>
  database: tiny_mini_test
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: tiny_mini_production
  adapter: mysql2
